version: '3.7'
services:
  web:
    build: .
    ports:
      - "4000"
    volumes:
      - .:/code
      - /code/node_modules
      - /code/packages/server/node_modules
    # environment:
      # FLASK_ENV: development
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379"
